// <auto-generated />
using System;
using M2_in_api_2.Date;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace M2_in_api_2.Migrations
{
    [DbContext(typeof(ShorpDbContext))]
    [Migration("14000817144446_two")]
    partial class two
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("M2_in_api_2.Model.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("inproductsID");

                    b.HasKey("ID");

                    b.HasIndex("inproductsID");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("M2_in_api_2.Model.Create_a_user_account_login", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Fullname");

                    b.Property<int>("Password");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("useraccont");
                });

            modelBuilder.Entity("M2_in_api_2.Model.Product", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("NameMark");

                    b.Property<int>("Price");

                    b.HasKey("ID");

                    b.ToTable("products");
                });

            modelBuilder.Entity("M2_in_api_2.Model.Category", b =>
                {
                    b.HasOne("M2_in_api_2.Model.Product", "inproducts")
                        .WithMany("categories")
                        .HasForeignKey("inproductsID");
                });
#pragma warning restore 612, 618
        }
    }
}
